server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /install {
        default_type text/plain;
        try_files /install.sh =404;
    }

    location /releases/ {
        default_type application/octet-stream;
        add_header Content-Disposition "attachment";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff2)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }
}
