run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - gofmt
    - goimports
    - ineffassign
    - unused

linters-settings:
  goimports:
    local-prefixes: github.com/IANTHEREAL/agent0

issues:
  max-same-issues: 0

