DROP TABLE IF EXISTS public.alter_add_identity_empty;
DROP TABLE IF EXISTS public.alter_add_identity_always;
DROP TABLE IF EXISTS public.alter_add_identity_by_default;
DROP TABLE IF EXISTS public.alter_add_bigserial_backfill;

-- Empty table + GENERATED ALWAYS AS IDENTITY: first inserted row should get 1.
CREATE TABLE public.alter_add_identity_empty (payload TEXT);
ALTER TABLE public.alter_add_identity_empty
    ADD COLUMN id BIGINT GENERATED ALWAYS AS IDENTITY;
INSERT INTO public.alter_add_identity_empty(payload) VALUES ('r1');
SELECT 'empty_always_next=' || id::text AS probe
FROM public.alter_add_identity_empty
WHERE payload = 'r1';

-- Non-empty table + GENERATED ALWAYS AS IDENTITY: existing rows get 1,2,3; next insert gets 4.
CREATE TABLE public.alter_add_identity_always (payload TEXT);
INSERT INTO public.alter_add_identity_always(payload) VALUES ('a'), ('b'), ('c');
ALTER TABLE public.alter_add_identity_always
    ADD COLUMN id BIGINT GENERATED ALWAYS AS IDENTITY;
SELECT 'always_backfill=' || string_agg(id::text, ',' ORDER BY id) AS probe
FROM public.alter_add_identity_always;
INSERT INTO public.alter_add_identity_always(payload) VALUES ('d');
SELECT 'always_next=' || id::text AS probe
FROM public.alter_add_identity_always
WHERE payload = 'd';

-- Non-empty table + GENERATED BY DEFAULT AS IDENTITY: existing rows get 1,2; next insert gets 3.
CREATE TABLE public.alter_add_identity_by_default (payload TEXT);
INSERT INTO public.alter_add_identity_by_default(payload) VALUES ('x'), ('y');
ALTER TABLE public.alter_add_identity_by_default
    ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
SELECT 'by_default_backfill=' || string_agg(id::text, ',' ORDER BY id) AS probe
FROM public.alter_add_identity_by_default;
INSERT INTO public.alter_add_identity_by_default(payload) VALUES ('z');
SELECT 'by_default_next=' || id::text AS probe
FROM public.alter_add_identity_by_default
WHERE payload = 'z';

-- Non-empty table + BIGSERIAL: existing rows get 1..5; next insert gets 6.
CREATE TABLE public.alter_add_bigserial_backfill (payload TEXT);
INSERT INTO public.alter_add_bigserial_backfill(payload)
VALUES ('p1'), ('p2'), ('p3'), ('p4'), ('p5');
ALTER TABLE public.alter_add_bigserial_backfill
    ADD COLUMN id BIGSERIAL;
SELECT 'bigserial_backfill=' || string_agg(id::text, ',' ORDER BY id) AS probe
FROM public.alter_add_bigserial_backfill;
INSERT INTO public.alter_add_bigserial_backfill(payload) VALUES ('p6');
SELECT 'bigserial_next=' || id::text AS probe
FROM public.alter_add_bigserial_backfill
WHERE payload = 'p6';

DROP TABLE public.alter_add_identity_empty;
DROP TABLE public.alter_add_identity_always;
DROP TABLE public.alter_add_identity_by_default;
DROP TABLE public.alter_add_bigserial_backfill;
