#!/usr/bin/env python3
"""Parse a pytest-json-report from the psycopg suite -> regenerate psycopg-bank.md.

Records every failing case verbatim (nodeid + exact db9 error), grouped by root
cause. Key enrichment: psycopg ships `@pytest.mark.crdb_skip` — tests CockroachDB
(also a distributed PG-compatible engine) skips. A db9 failure that is ALSO
crdb_skip is an *expected distributed-engine divergence*; a failure that is NOT
crdb_skip is db9-specific (even CRDB passes it) and more concerning.

Usage: classify_failures.py <report.json> <psycopg_dir> <output_md>
"""
import glob
import json
import os
import re
import sys
from collections import defaultdict

KNOWN = [
    ("could not determine data type of parameter", ("Extended-protocol parameter type inference ($N indeterminate)", "types/protocol")),
    ("found: DEFERRABLE", ("DEFERRABLE transaction syntax (BEGIN/SET TRANSACTION ... DEFERRABLE) not parsed", "parser/txn")),
    ("PG_TERMINATE_BACKEND", ("pg_terminate_backend() unsupported", "functions/admin")),
    ("PG_CANCEL_BACKEND", ("pg_cancel_backend() unsupported", "functions/admin")),
    ("transaction_read_only", ("transaction_read_only GUC unrecognized", "session/guc")),
    ("must appear in the GROUP BY", ("GROUP BY primary-key functional dependency (see #2701)", "analyzer/group_by")),
    ("SET CONSTRAINTS", ("SET CONSTRAINTS ALL not parsed (see #2702)", "parser")),
    ('type "', ("missing type", "types")),
    ("unknown function", ("unknown function", "functions")),
    ("current transaction is aborted", ("cascade (downstream of a prior error)", "cascade")),
    ("statement timeout", ("statement timeout firing (db9 defaults statement_timeout=60s; PG default is 0/unlimited)", "session/timeout")),
    ("does not exist", ("relation/object missing — cascade of a failed setup statement", "cascade")),
    ("unrecognized configuration parameter", ("unrecognized GUC", "session/guc")),
]


def classify(msg):
    for sub, info in KNOWN:
        if sub.lower() in msg.lower():
            return info
    if "AssertionError" in msg:
        return ("result/behavior mismatch (assertion)", "behavior")
    return ("untriaged", "—")


def err_of(t):
    for ph in ("call", "setup", "teardown"):
        sec = t.get(ph) or {}
        crash = sec.get("crash") or {}
        if crash.get("message"):
            return crash["message"].splitlines()[-1].strip()
        if sec.get("longrepr"):
            return str(sec["longrepr"]).splitlines()[-1].strip()
    return "(no message)"


def main():
    results_dir, _psycopg_dir, out_md = sys.argv[1], sys.argv[2], sys.argv[3]
    tests = []
    npass = nfail = nerr = nskip = 0
    for rp in sorted(glob.glob(os.path.join(results_dir, "*.json"))):
        d = json.load(open(rp))
        tests.extend(d.get("tests", []))
        s = d.get("summary", {})
        npass += s.get("passed", 0); nfail += s.get("failed", 0)
        nerr += s.get("error", 0); nskip += s.get("skipped", 0)
    crashed = [open(c).read().strip() for c in sorted(glob.glob(os.path.join(results_dir, "*.crashed")))]
    fails = [t for t in tests if t.get("outcome") in ("failed", "error")]

    groups = defaultdict(list)
    crdb_overlap = 0
    for t in fails:
        msg = err_of(t)
        is_crdb = "crdb_skip" in (t.get("keywords") or [])
        if is_crdb:
            crdb_overlap += 1
        groups[classify(msg)].append((t["nodeid"], msg, is_crdb))

    total = npass + nfail + nerr + nskip
    db9_specific = len(fails) - crdb_overlap

    o = []
    W = o.append
    W("# psycopg Driver Bank — db9 PostgreSQL-Compatibility Validation\n")
    W("> Auto-generated by `classify_failures.py` from the latest `run.sh` pass. Runs")
    W("> **psycopg3's own test suite** against db9 — the connect-path surface (extended")
    W("> protocol, type/OID codecs, SQLSTATE, COPY, txn control) that the pg_regress and")
    W("> Django lanes don't reach. Re-run: `bash auto_testing/corpora/drivers/psycopg/run.sh`.\n")
    W("> ⚠️ **Smoke tier** — core DB-behavior test files (psycopg 3.3.4), excluding mypy/")
    W("> lint/packaging meta-tests (not db9 gaps). Full suite: `run.sh full`.\n")
    W(f"**Tests:** {total} · **Pass:** {npass} ({round(100*npass/total) if total else 0}%) · "
      f"**Fail:** {nfail} · **Error:** {nerr} · **Skipped:** {nskip}\n")
    if crashed:
        W(f"> ⚠️ **{len(crashed)} test file(s) crashed/hung the pytest session** (no report — itself")
        W(f"> a db9 gap, likely an unsupported wire feature or a hang): `{', '.join(crashed)}`\n")
    W("### CRDB cross-reference (distributed-engine divergence vs db9-specific)\n")
    W(f"psycopg marks {crdb_overlap and 'some' or 'no'} of these failures `@crdb_skip` — i.e.")
    W("CockroachDB (also a distributed PG engine) skips them, so they are *expected")
    W("distributed-engine divergences*, not necessarily db9 bugs:\n")
    W(f"- **{crdb_overlap}** failures are **also crdb_skip** → expected distributed divergence (lower priority).")
    W(f"- **{db9_specific}** failures are **db9-specific** (CRDB passes them) → the real db9 gaps to prioritize.\n")
    W("## Root causes (by blast radius)\n")
    W("| Root cause | Fault layer | Cases | …of which db9-specific |")
    W("|---|---|---|---|")
    for (name, layer), items in sorted(groups.items(), key=lambda x: -len(x[1])):
        spec = sum(1 for _, _, c in items if not c)
        W(f"| {name} | {layer} | {len(items)} | {spec} |")
    W("")
    W("## Every failing case (verbatim)\n")
    W("`[db9]` = db9-specific (CRDB passes it); `[dist]` = also crdb_skip (expected distributed divergence).\n")
    W("| Tag | Test | db9 error (verbatim) |")
    W("|---|---|---|")
    for t in sorted(fails, key=lambda x: x["nodeid"]):
        msg = err_of(t).replace("|", chr(92) + "|")[:200]
        tag = "dist" if "crdb_skip" in (t.get("keywords") or []) else "db9"
        W(f"| {tag} | `{t['nodeid']}` | {msg} |")
    W("")
    W("## Reproduce one case\n```bash")
    W("bash auto_testing/corpora/drivers/psycopg/run.sh tests/test_connection.py")
    W("# single test (db9 on :5455):")
    W('PSYCOPG_TEST_DSN="host=127.0.0.1 port=5455 user=admin password=admin dbname=psycopg_test" \\')
    W("  /tmp/pgvenv/bin/python -m pytest /tmp/psycopg/tests/<file>::<test> -q --tb=short")
    W("```")
    open(out_md, "w").write("\n".join(o))
    print(f"wrote {out_md}: {total} tests, {len(fails)} failures "
          f"({db9_specific} db9-specific, {crdb_overlap} crdb-overlap), {len(crashed)} crashed-files")


if __name__ == "__main__":
    main()
