#!/usr/bin/env python3
"""Parse Django runtests logs (results/<app>.log) -> regenerate Django-bank.md.

Records every failing case verbatim (test id + exact db9 error), grouped by
root cause. Known root causes are annotated with their tracking issue. Re-run by
run.sh after every test pass, so the report always reflects the latest run.

Usage: classify_failures.py <results_dir> <output_md>
"""
import os
import re
import sys
from collections import defaultdict

# Known db9 gaps: substring in the error -> (short name, issue, fault layer).
# Extend as new gaps are triaged. Anything unmatched is listed as "untriaged".
KNOWN = [
    ("must appear in the GROUP BY", ("GROUP BY primary-key functional dependency", "#2701", "analyzer/group_by")),
    ("SET CONSTRAINTS",             ("SET CONSTRAINTS ALL not parsed",             "#2702", "parser")),
    ('type "inet"',                 ("inet type missing",                          "#2703", "types")),
    ("subquery expressions must be resolved", ("correlated subquery executor-level", "#2704", "optimizer/executor")),
    ("interval",                    ("INTERVAL/duration handling",                 "#2706", "types/interval")),
    ("COALESCE types",              ("INTERVAL/duration handling",                 "#2706", "types/interval")),
    ("STDDEV", ("long-tail (aggregate fn)", "#2707", "functions/aggregate")),
    ("time zone", ("long-tail (timezone names)", "#2707", "datetime/tz")),
    ("Declare", ("long-tail (DECLARE CURSOR)", "#2707", "parser")),
    ("cast type", ("long-tail (cast)", "#2707", "types/cast")),
    ("pg_get_serial_sequence", ("pg_get_serial_sequence in setval()", "#2707", "functions")),
    ("current transaction is aborted", ("cascade (downstream of a prior error)", "(cascade)", "—")),
]
SEP, DASH = "=" * 70, "-" * 70


def classify(err):
    for sub, info in KNOWN:
        if sub.lower() in err.lower():
            return info
    if "AssertionError" in err:
        return ("result mismatch (wrong value/order)", "(untriaged)", "—")
    return ("untriaged", "(untriaged)", "—")


def parse_app(path):
    txt = open(path, errors="replace").read()
    ran = re.search(r"^Ran (\d+) tests", txt, re.M)
    setup_err = None
    if not ran:
        exc = [l for l in txt.splitlines() if re.match(r"^\w[\w\.]*(Error|Exception):", l)]
        setup_err = exc[-1].strip() if exc else "setup failed; no test ran"
    fails = []
    for part in txt.split(SEP):
        m = re.match(r"\s*(FAIL|ERROR):\s+(\S+)", part.strip())
        if not m:
            continue
        body = part.split(DASH, 1)[1] if DASH in part else part
        lines = [l for l in body.splitlines() if l.strip()]
        exc = ""
        for l in lines:
            if re.match(r"^\w[\w\.]*(Error|Exception|NotSupported|Warning):", l):
                exc = l.strip()
        if not exc and lines:
            exc = lines[-1].strip()
        fails.append((m.group(1), m.group(2), exc))
    return {"ran": int(ran.group(1)) if ran else 0, "setup_err": setup_err, "fails": fails}


def main():
    results_dir, out_md = sys.argv[1], sys.argv[2]
    apps = sorted(f[:-4] for f in os.listdir(results_dir) if f.endswith(".log"))
    data = {a: parse_app(os.path.join(results_dir, f"{a}.log")) for a in apps}

    groups = defaultdict(list)
    tot = tp = tf = te = 0
    for a in apps:
        d = data[a]
        nf = sum(1 for k, _, _ in d["fails"] if k == "FAIL")
        ne = sum(1 for k, _, _ in d["fails"] if k == "ERROR")
        tot += d["ran"]; tf += nf; te += ne; tp += d["ran"] - nf - ne
        for kind, test, err in d["fails"]:
            groups[classify(err)].append((a, test, err))

    o = []
    W = o.append
    W("# Django Test Bank — db9 PostgreSQL-Compatibility Validation\n")
    W("> Auto-generated by `classify_failures.py` from the latest `run.sh` pass. Records")
    W("> every failing case verbatim (test id + exact db9 error), grouped by root cause.")
    W("> Re-run: `bash auto_testing/corpora/django/run.sh [smoke|full|<apps>]`.\n")
    ran_apps = [a for a in apps if not data[a]["setup_err"]]
    W(f"**Modules run:** {len(apps)} (Django has 213) · **Tests:** {tot} · "
      f"**Pass:** {tp} ({round(100*tp/tot) if tot else 0}%) · **Fail:** {tf} · **Error:** {te}\n")
    W("## Results by module\n")
    W("| Module | Ran | Pass | Fail | Error | Note |")
    W("|---|---|---|---|---|---|")
    for a in apps:
        d = data[a]
        if d["setup_err"]:
            W(f"| {a} | 0 | 0 | 0 | 0 | setup blocked: `{d['setup_err'][:60]}` |")
        else:
            nf = sum(1 for k, _, _ in d["fails"] if k == "FAIL")
            ne = sum(1 for k, _, _ in d["fails"] if k == "ERROR")
            W(f"| {a} | {d['ran']} | {d['ran']-nf-ne} | {nf} | {ne} | |")
    W("")
    W("## Root causes (by blast radius)\n")
    W("| Root cause | Issue | Fault layer | Cases |")
    W("|---|---|---|---|")
    for (name, issue, layer), items in sorted(groups.items(), key=lambda x: -len(x[1])):
        W(f"| {name} | {issue} | {layer} | {len(items)} |")
    W("")
    W("## Every failing case (verbatim)\n")
    for a in apps:
        d = data[a]
        if d["setup_err"]:
            W(f"### `{a}` — setup blocked\n\n> `{d['setup_err']}`\n")
            continue
        if not d["fails"]:
            W(f"### `{a}` — all pass\n")
            continue
        W(f"### `{a}`\n")
        W("| Kind | Test | db9 error (verbatim) |")
        W("|---|---|---|")
        for kind, test, err in sorted(d["fails"]):
            W(f"| {kind} | `{test}` | {err.replace('|', chr(92)+'|')[:200]} |")
        W("")
    W("## Reproduce one case\n```bash")
    W("bash auto_testing/corpora/django/run.sh <module>   # or a single test:")
    W("DJANGO_DIR=/tmp/django VENV=/tmp/djvenv PYTHONPATH=auto_testing/corpora/django:/tmp/django/tests \\")
    W("  /tmp/djvenv/bin/python /tmp/django/tests/runtests.py --settings=db9_settings \\")
    W("  --parallel=1 --verbosity=2 <module>.<Class>.<test>")
    W("```")
    open(out_md, "w").write("\n".join(o))
    print(f"wrote {out_md}: {tot} tests, {tf+te} failures, {len(groups)} root-cause groups")


if __name__ == "__main__":
    main()
