use super::validate::*;
use super::*;

/// Look up a GUC definition by canonical name.
pub(crate) fn find_guc_def(canonical: &str) -> Option<&'static GucDef> {
    GUC_TABLE.iter().find(|g| g.name == canonical)
}

/// Single source of truth for all known GUC parameters. MUST be sorted alphabetically by name.
pub(crate) const GUC_TABLE: &[GucDef] = &[
    GucDef {
        name: "application_name",
        guc_type: GucType::String,
        context: GucContext::Userset,
        description: "",
        boot_default: "",
        flags: GUC_REPORT,
        validate_fn: None,
    },
    GucDef {
        name: "bytea_output",
        guc_type: GucType::Enum,
        context: GucContext::Userset,
        description: "",
        boot_default: "hex",
        flags: 0,
        validate_fn: Some(validate_bytea_output),
    },
    GucDef {
        name: "check_function_bodies",
        guc_type: GucType::Bool,
        context: GucContext::Userset,
        description: "pg_dump compat; no PL/pgSQL body validation implemented",
        boot_default: "on",
        flags: GUC_HOLLOW,
        validate_fn: None,
    },
    GucDef {
        name: "client_encoding",
        guc_type: GucType::String,
        context: GucContext::Userset,
        description: "",
        boot_default: "UTF8",
        flags: GUC_REPORT,
        validate_fn: Some(validate_client_encoding),
    },
    GucDef {
        name: "client_min_messages",
        guc_type: GucType::String,
        context: GucContext::Userset,
        description: "",
        boot_default: "notice",
        flags: 0,
        validate_fn: None,
    },
    GucDef {
        name: "datestyle",
        guc_type: GucType::String,
        context: GucContext::Userset,
        description: "",
        boot_default: "ISO, MDY",
        flags: GUC_REPORT,
        validate_fn: Some(validate_datestyle),
    },
    GucDef {
        name: "db9.dml_table_scan_max_rows",
        guc_type: GucType::String,
        context: GucContext::Userset,
        description:
            "Maximum rows per auxiliary source and combined cross-product cap for UPDATE FROM / DELETE USING (0 = unlimited)",
        boot_default: "",
        flags: GUC_RUNTIME_DEFAULT,
        validate_fn: Some(validate_db9_dml_table_scan_max_rows),
    },
    GucDef {
        name: "db9.enable_cop_pushdown",
        guc_type: GucType::Bool,
        context: GucContext::Userset,
        description: "Enable DB9 coprocessor pushdown planning",
        boot_default: "off",
        flags: 0,
        validate_fn: Some(validate_db9_enable_cop_pushdown),
    },
    GucDef {
        name: "db9.hash_join_work_mem",
        guc_type: GucType::ByteSize,
        context: GucContext::Userset,
        description: "Maximum memory for hash join build side (0 = unlimited)",
        boot_default: "",
        flags: GUC_RUNTIME_DEFAULT,
        validate_fn: None,
    },
    GucDef {
        name: "db9.max_sort_bytes",
        guc_type: GucType::ByteSize,
        context: GucContext::Userset,
        description: "",
        boot_default: "",
        flags: GUC_RUNTIME_DEFAULT,
        validate_fn: None,
    },
    GucDef {
        name: "db9.password_grace_seconds",
        guc_type: GucType::Int,
        context: GucContext::Userset,
        description: "Grace period in seconds for the old password after ALTER ROLE WITH PASSWORD (0 = immediate replacement)",
        boot_default: "0",
        flags: 0,
        validate_fn: Some(validate_db9_password_grace_seconds),
    },
    GucDef {
        name: "db9.prepared_plan_cache_min_exec",
        guc_type: GucType::Int,
        context: GucContext::Userset,
        description: "",
        boot_default: "5",
        flags: 0,
        validate_fn: Some(validate_db9_positive_u64),
    },
    GucDef {
        name: "db9.prepared_plan_cache_size",
        guc_type: GucType::Int,
        context: GucContext::Userset,
        description: "",
        boot_default: "128",
        flags: 0,
        validate_fn: Some(validate_db9_positive_u64),
    },
    GucDef {
        name: "db9.retry_max_attempts",
        guc_type: GucType::Int,
        context: GucContext::Userset,
        description: "Maximum retry attempts for autocommit DML/DDL on write conflict",
        boot_default: "64",
        flags: 0,
        validate_fn: Some(validate_db9_retry_max_attempts),
    },
    GucDef {
        name: "db9.retry_timeout",
        guc_type: GucType::Timeout,
        context: GucContext::Userset,
        description: "Maximum wall-time for retries per statement (0 = no limit)",
        boot_default: "0",
        flags: 0,
        validate_fn: None,
    },
    GucDef {
        name: "db9.use_optimizer",
        guc_type: GucType::Bool,
        context: GucContext::Userset,
        description: "Always-on optimizer (accepted for compat, SET off is a no-op)",
        boot_default: "on",
        flags: GUC_HOLLOW,
        validate_fn: Some(validate_db9_use_optimizer),
    },
    GucDef {
        name: "default_table_access_method",
        guc_type: GucType::String,
        context: GucContext::Userset,
        description: "",
        boot_default: "heap",
        flags: 0,
        validate_fn: None,
    },
    GucDef {
        name: "default_tablespace",
        guc_type: GucType::String,
        context: GucContext::Userset,
        description: "",
        boot_default: "",
        flags: 0,
        validate_fn: Some(validate_default_tablespace),
    },
    GucDef {
        name: "default_text_search_config",
        guc_type: GucType::String,
        context: GucContext::Userset,
        description: "",
        boot_default: "",
        flags: GUC_RUNTIME_DEFAULT,
        validate_fn: None,
    },
    GucDef {
        name: "default_transaction_deferrable",
        guc_type: GucType::Bool,
        context: GucContext::Userset,
        description: "DEFERRABLE transactions require SERIALIZABLE isolation, which is not supported",
        boot_default: "off",
        flags: 0,
        validate_fn: Some(validate_default_transaction_deferrable),
    },
    GucDef {
        name: "default_transaction_isolation",
        guc_type: GucType::Enum,
        context: GucContext::Userset,
        description: "",
        boot_default: "read committed",
        flags: 0,
        validate_fn: Some(validate_transaction_isolation),
    },
    GucDef {
        name: "default_transaction_read_only",
        guc_type: GucType::Bool,
        context: GucContext::Userset,
        description: "",
        boot_default: "off",
        flags: 0,
        validate_fn: Some(validate_default_transaction_read_only),
    },
    GucDef {
        name: "embedding.api_key",
        guc_type: GucType::String,
        context: GucContext::Userset,
        description: "Embedding service API key (session override)",
        boot_default: "",
        flags: 0,
        validate_fn: Some(validate_embedding_api_key),
    },
    GucDef {
        name: "embedding.concurrency",
        guc_type: GucType::Int,
        context: GucContext::Userset,
        description: "",
        boot_default: "5",
        flags: 0,
        validate_fn: Some(validate_embedding_positive_u32),
    },
    GucDef {
        name: "embedding.dimensions",
        guc_type: GucType::Int,
        context: GucContext::Userset,
        description: "",
        boot_default: "",
        flags: GUC_RUNTIME_DEFAULT,
        validate_fn: Some(validate_embedding_dimensions),
    },
    GucDef {
        name: "embedding.endpoint",
        guc_type: GucType::String,
        context: GucContext::Userset,
        description: "Embedding service endpoint URL (session override)",
        boot_default: "",
        flags: GUC_RUNTIME_DEFAULT,
        validate_fn: Some(validate_embedding_endpoint),
    },
    GucDef {
        name: "embedding.max_calls",
        guc_type: GucType::Int,
        context: GucContext::Userset,
        description: "",
        boot_default: "100",
        flags: 0,
        validate_fn: Some(validate_embedding_positive_u32),
    },
    GucDef {
        name: "embedding.model",
        guc_type: GucType::String,
        context: GucContext::Userset,
        description: "",
        boot_default: "",
        flags: GUC_RUNTIME_DEFAULT,
        validate_fn: Some(validate_embedding_model),
    },
    GucDef {
        name: "embedding.provider",
        guc_type: GucType::String,
        context: GucContext::Userset,
        description: "Embedding provider: openai or bedrock (session override)",
        boot_default: "",
        flags: GUC_RUNTIME_DEFAULT,
        validate_fn: Some(validate_embedding_provider),
    },
    GucDef {
        name: "extra_float_digits",
        guc_type: GucType::Int,
        context: GucContext::Userset,
        description: "",
        boot_default: "1",
        flags: 0,
        validate_fn: None,
    },
    GucDef {
        name: "hnsw.ef_search",
        guc_type: GucType::Int,
        context: GucContext::Userset,
        description: "Sets the size of the dynamic candidate list for HNSW index search.",
        boot_default: "40",
        flags: 0,
        validate_fn: Some(validate_hnsw_ef_search),
    },
    GucDef {
        name: "idle_in_transaction_session_timeout",
        guc_type: GucType::Timeout,
        context: GucContext::Userset,
        description: "",
        boot_default: "0",
        flags: 0,
        validate_fn: None,
    },
    GucDef {
        name: "in_hot_standby",
        guc_type: GucType::Bool,
        context: GucContext::Internal,
        description: "",
        boot_default: "off",
        flags: 0,
        validate_fn: None,
    },
    GucDef {
        name: "integer_datetimes",
        guc_type: GucType::Bool,
        context: GucContext::Internal,
        description: "",
        boot_default: "on",
        flags: 0,
        validate_fn: None,
    },
    GucDef {
        name: "intervalstyle",
        guc_type: GucType::String,
        context: GucContext::Userset,
        description: "",
        boot_default: "postgres",
        flags: GUC_REPORT,
        validate_fn: Some(validate_intervalstyle),
    },
    GucDef {
        name: "lc_messages",
        guc_type: GucType::String,
        context: GucContext::Suset,
        description: "",
        boot_default: "C",
        flags: 0,
        validate_fn: None,
    },
    GucDef {
        name: "lc_monetary",
        guc_type: GucType::String,
        context: GucContext::Userset,
        description: "",
        boot_default: "C",
        flags: 0,
        validate_fn: None,
    },
    GucDef {
        name: "lc_numeric",
        guc_type: GucType::String,
        context: GucContext::Userset,
        description: "",
        boot_default: "C",
        flags: 0,
        validate_fn: None,
    },
    GucDef {
        name: "lc_time",
        guc_type: GucType::String,
        context: GucContext::Userset,
        description: "",
        boot_default: "C",
        flags: 0,
        validate_fn: None,
    },
    GucDef {
        name: "lock_timeout",
        guc_type: GucType::Timeout,
        context: GucContext::Userset,
        description: "",
        boot_default: "0",
        flags: 0,
        validate_fn: None,
    },
    GucDef {
        name: "max_identifier_length",
        guc_type: GucType::Int,
        context: GucContext::Internal,
        description: "",
        boot_default: "63",
        flags: 0,
        validate_fn: None,
    },
    GucDef {
        name: "max_index_keys",
        guc_type: GucType::Int,
        context: GucContext::Internal,
        description: "",
        boot_default: "32",
        flags: 0,
        validate_fn: None,
    },
    GucDef {
        name: "password_encryption",
        guc_type: GucType::String,
        context: GucContext::Userset,
        description: "",
        boot_default: "scram-sha-256",
        flags: 0,
        validate_fn: None,
    },
    GucDef {
        name: "row_security",
        guc_type: GucType::Bool,
        context: GucContext::Userset,
        description: "",
        boot_default: "on",
        flags: 0,
        validate_fn: None,
    },
    GucDef {
        name: "search_path",
        guc_type: GucType::String,
        context: GucContext::Userset,
        description: "",
        boot_default: "\"$user\", public",
        flags: GUC_REPORT,
        validate_fn: None,
    },
    GucDef {
        name: "server_encoding",
        guc_type: GucType::String,
        context: GucContext::Internal,
        description: "",
        boot_default: "UTF8",
        flags: GUC_REPORT,
        validate_fn: None,
    },
    GucDef {
        name: "server_version",
        guc_type: GucType::String,
        context: GucContext::Internal,
        description: "",
        boot_default: "16.0",
        flags: GUC_REPORT,
        validate_fn: None,
    },
    GucDef {
        name: "server_version_num",
        guc_type: GucType::Int,
        context: GucContext::Internal,
        description: "",
        boot_default: "160000",
        flags: 0,
        validate_fn: None,
    },
    GucDef {
        name: "session_replication_role",
        guc_type: GucType::String,
        context: GucContext::Userset,
        description: "session_replication_role is not supported; triggers always fire as in \"origin\" mode",
        boot_default: "origin",
        flags: 0,
        validate_fn: Some(validate_session_replication_role),
    },
    GucDef {
        name: "standard_conforming_strings",
        guc_type: GucType::Bool,
        context: GucContext::Userset,
        description: "",
        boot_default: "on",
        flags: GUC_REPORT,
        validate_fn: Some(validate_standard_conforming_strings),
    },
    GucDef {
        name: "statement_timeout",
        guc_type: GucType::Timeout,
        context: GucContext::Userset,
        description: "",
        boot_default: "0",
        flags: 0,
        validate_fn: None,
    },
    GucDef {
        name: "timezone",
        guc_type: GucType::String,
        context: GucContext::Userset,
        description: "",
        boot_default: "UTC",
        flags: GUC_REPORT,
        validate_fn: Some(validate_timezone),
    },
    GucDef {
        name: "transaction_deferrable",
        guc_type: GucType::Bool,
        context: GucContext::Userset,
        description: "DEFERRABLE transactions require SERIALIZABLE isolation, which is not supported",
        boot_default: "off",
        flags: 0,
        validate_fn: Some(validate_transaction_deferrable),
    },
    GucDef {
        name: "transaction_isolation",
        guc_type: GucType::Enum,
        context: GucContext::Userset,
        description: "",
        boot_default: "repeatable read",
        flags: 0,
        validate_fn: Some(validate_transaction_isolation),
    },
    GucDef {
        name: "work_mem",
        guc_type: GucType::String,
        context: GucContext::Userset,
        description: "",
        boot_default: "4MB",
        flags: GUC_HOLLOW,
        validate_fn: None,
    },
    GucDef {
        name: "xmloption",
        guc_type: GucType::String,
        context: GucContext::Userset,
        description: "",
        boot_default: "content",
        flags: 0,
        validate_fn: None,
    },
];
