// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitVolumeRequest {
    #[prost(string, tag = "1")]
    pub volume_id: ::prost::alloc::string::String,
    /// JuiceFS meta URL, e.g.:
    /// "tikv://pd:2379?keyspace=jfs_t_{tenant}&gc-interval=0&ca=...&cert=...&key=..."
    #[prost(string, tag = "2")]
    pub meta_url: ::prost::alloc::string::String,
    /// Chunk cache size in MB. 0 = use server default.
    #[prost(uint32, tag = "3")]
    pub cache_size_mb: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitVolumeResponse {
    /// True if newly initialized, false if already active.
    #[prost(bool, tag = "1")]
    pub created: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CloseVolumeRequest {
    #[prost(string, tag = "1")]
    pub volume_id: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CloseVolumeResponse {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReadAtRequest {
    #[prost(string, tag = "1")]
    pub volume_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub offset: u64,
    /// 0 = read to end of file.
    #[prost(uint64, tag = "4")]
    pub length: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReadAtResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// Total file size. Set only on the first chunk; 0 on subsequent.
    #[prost(uint64, tag = "2")]
    pub file_size: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatRequest {
    #[prost(string, tag = "1")]
    pub volume_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatResponse {
    #[prost(uint64, tag = "1")]
    pub size: u64,
    /// Last modification time as Unix milliseconds.
    #[prost(int64, tag = "2")]
    pub mtime_ms: i64,
    #[prost(uint32, tag = "3")]
    pub mode: u32,
    #[prost(bool, tag = "4")]
    pub is_dir: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReaddirRequest {
    #[prost(string, tag = "1")]
    pub volume_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReaddirResponse {
    #[prost(message, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<DirEntry>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DirEntry {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub is_dir: bool,
    #[prost(uint64, tag = "3")]
    pub size: u64,
    #[prost(int64, tag = "4")]
    pub mtime_ms: i64,
    #[prost(uint32, tag = "5")]
    pub mode: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PutFileRequest {
    #[prost(string, tag = "1")]
    pub volume_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(enumeration = "WriteMode", tag = "3")]
    pub mode: i32,
    #[prost(uint32, tag = "4")]
    pub file_mode: u32,
    #[prost(uint32, tag = "5")]
    pub umask: u32,
    /// Payload. Server MUST reject if > 4 MiB (use BeginWrite/WriteParts/CommitWrite
    /// for anything larger).
    #[prost(bytes = "vec", tag = "6")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PutFileResponse {
    #[prost(uint64, tag = "1")]
    pub new_size: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BeginWriteRequest {
    #[prost(string, tag = "1")]
    pub volume_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(enumeration = "WriteMode", tag = "3")]
    pub mode: i32,
    #[prost(uint32, tag = "4")]
    pub file_mode: u32,
    #[prost(uint32, tag = "5")]
    pub umask: u32,
    /// Optional upper bound on total bytes. Server fast-fails at WritePart when
    /// cumulative would exceed this; re-checked at Commit.
    #[prost(uint64, optional, tag = "6")]
    pub expected_size: ::core::option::Option<u64>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BeginWriteResponse {
    /// Opaque, 128-bit random, unguessable.
    #[prost(string, tag = "1")]
    pub upload_id: ::prost::alloc::string::String,
    /// Recommended max bytes per WritePartRequest.data. Default 4 MiB.
    ///
    /// NO expires_at — server is authoritative on TTL; client must not compute
    /// "time remaining" from a wire value (clock skew hazard).
    #[prost(uint64, tag = "2")]
    pub part_size_hint: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WritePartRequest {
    #[prost(string, tag = "1")]
    pub upload_id: ::prost::alloc::string::String,
    /// MUST equal the server's cumulative bytes_received; FAILED_PRECONDITION
    /// otherwise. Strict in-order, no gaps, no overlap.
    #[prost(uint64, tag = "2")]
    pub offset: u64,
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WritePartsResponse {
    /// Cumulative bytes successfully staged by this stream.
    #[prost(uint64, tag = "1")]
    pub bytes_received: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommitWriteRequest {
    #[prost(string, tag = "1")]
    pub upload_id: ::prost::alloc::string::String,
    /// MUST equal server bytes_received; FAILED_PRECONDITION otherwise.
    #[prost(uint64, tag = "2")]
    pub total_size: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommitWriteResponse {
    #[prost(uint64, tag = "1")]
    pub new_size: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AbortWriteRequest {
    #[prost(string, tag = "1")]
    pub upload_id: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AbortWriteResponse {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WriteAtRequest {
    #[prost(string, tag = "1")]
    pub volume_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub offset: u64,
    #[prost(bytes = "vec", tag = "4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "5")]
    pub flush: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WriteAtResponse {
    #[prost(uint64, tag = "1")]
    pub bytes_written: u64,
    #[prost(uint64, tag = "2")]
    pub new_size: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TruncateRequest {
    #[prost(string, tag = "1")]
    pub volume_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub size: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TruncateResponse {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteRequest {
    #[prost(string, tag = "1")]
    pub volume_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteResponse {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MkdirRequest {
    #[prost(string, tag = "1")]
    pub volume_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub mode: u32,
    #[prost(uint32, tag = "4")]
    pub umask: u32,
    #[prost(bool, tag = "5")]
    pub recursive: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MkdirResponse {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RenameRequest {
    #[prost(string, tag = "1")]
    pub volume_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub old_path: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub new_path: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RenameResponse {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SymlinkRequest {
    #[prost(string, tag = "1")]
    pub volume_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub target: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub link: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SymlinkResponse {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReadlinkRequest {
    #[prost(string, tag = "1")]
    pub volume_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReadlinkResponse {
    #[prost(string, tag = "1")]
    pub target: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChmodRequest {
    #[prost(string, tag = "1")]
    pub volume_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub mode: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChmodResponse {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AdvanceNextChunkRequest {
    #[prost(string, tag = "1")]
    pub volume_id: ::prost::alloc::string::String,
    /// Number to add to the nextChunk counter. Use 1<<40 (1099511627776) for
    /// standard clone safety margin.
    #[prost(int64, tag = "2")]
    pub offset: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AdvanceNextChunkResponse {
    /// The new value of the nextChunk counter after advancing.
    #[prost(int64, tag = "1")]
    pub new_value: i64,
    /// The old value before advancing.
    #[prost(int64, tag = "2")]
    pub old_value: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FlushRequest {
    #[prost(string, tag = "1")]
    pub volume_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FlushResponse {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PingRequest {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PingResponse {
    #[prost(uint32, tag = "1")]
    pub active_volumes: u32,
    #[prost(uint64, tag = "2")]
    pub rss_bytes: u64,
}
/// WriteMode selects the publish semantic at CommitWrite / PutFile time.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum WriteMode {
    Unspecified = 0,
    /// REPLACE: atomic rename-over target.
    Replace = 1,
    /// CREATE_ONLY: atomic rename with RENAME_NOREPLACE; ALREADY_EXISTS on
    /// collision at commit.
    CreateOnly = 2,
    /// APPEND: concat to existing target under flock at commit.
    Append = 3,
}
impl WriteMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            WriteMode::Unspecified => "WRITE_MODE_UNSPECIFIED",
            WriteMode::Replace => "WRITE_MODE_REPLACE",
            WriteMode::CreateOnly => "WRITE_MODE_CREATE_ONLY",
            WriteMode::Append => "WRITE_MODE_APPEND",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "WRITE_MODE_UNSPECIFIED" => Some(Self::Unspecified),
            "WRITE_MODE_REPLACE" => Some(Self::Replace),
            "WRITE_MODE_CREATE_ONLY" => Some(Self::CreateOnly),
            "WRITE_MODE_APPEND" => Some(Self::Append),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod fs_plane_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// FsPlane is a thin gRPC proxy wrapping JuiceFS pkg/fs.FileSystem.
    ///
    /// It serves db9-server (Rust) as its only client over a Unix domain socket.
    /// The proxy holds no business logic — no CAS, no generation tracking, no
    /// idempotency, no authz. All intelligence stays in db9-server.
    ///
    /// Each RPC is self-contained: the proxy opens a JuiceFS file handle internally,
    /// performs the operation, optionally flushes, closes the handle, and returns.
    /// No file handles are exposed over the wire.
    ///
    /// Error mapping: JuiceFS syscall.Errno → gRPC status codes.
    /// The numeric errno is embedded in the status message as "[errno=N]"
    /// (e.g. "path: is a directory [errno=21]"). db9-server parses this for
    /// precise error mapping; the gRPC status code is a coarse fallback.
    ///
    ///   ENOENT (2)      → NOT_FOUND
    ///   EACCES (13)     → PERMISSION_DENIED
    ///   EEXIST (17)     → ALREADY_EXISTS
    ///   ENOTDIR (20)    → FAILED_PRECONDITION
    ///   EISDIR (21)     → FAILED_PRECONDITION
    ///   EINVAL (22)     → INVALID_ARGUMENT
    ///   ENOSPC (28)     → RESOURCE_EXHAUSTED
    ///   ENOTEMPTY (39)  → FAILED_PRECONDITION
    ///   EIO (5)         → INTERNAL
    ///   other           → UNKNOWN
    #[derive(Debug, Clone)]
    pub struct FsPlaneClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl FsPlaneClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> FsPlaneClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> FsPlaneClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            FsPlaneClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// InitVolume connects to an existing JuiceFS volume and initializes the
        /// in-process FileSystem instance. The volume must be pre-formatted with
        /// `juicefs format`. Idempotent: returns success if already initialized.
        pub async fn init_volume(
            &mut self,
            request: impl tonic::IntoRequest<super::InitVolumeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::InitVolumeResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/fsplane.v1.FsPlane/InitVolume",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("fsplane.v1.FsPlane", "InitVolume"));
            self.inner.unary(req, path, codec).await
        }
        /// CloseVolume disconnects from a volume, flushes pending data, closes
        /// the meta session, and frees memory.
        pub async fn close_volume(
            &mut self,
            request: impl tonic::IntoRequest<super::CloseVolumeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CloseVolumeResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/fsplane.v1.FsPlane/CloseVolume",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("fsplane.v1.FsPlane", "CloseVolume"));
            self.inner.unary(req, path, codec).await
        }
        /// ReadAt reads a byte range from a file and streams the result in chunks.
        /// If length is 0, reads from offset to end of file.
        pub async fn read_at(
            &mut self,
            request: impl tonic::IntoRequest<super::ReadAtRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ReadAtResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/fsplane.v1.FsPlane/ReadAt",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("fsplane.v1.FsPlane", "ReadAt"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// Stat returns file metadata (size, mtime, mode).
        pub async fn stat(
            &mut self,
            request: impl tonic::IntoRequest<super::StatRequest>,
        ) -> std::result::Result<tonic::Response<super::StatResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/fsplane.v1.FsPlane/Stat");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("fsplane.v1.FsPlane", "Stat"));
            self.inner.unary(req, path, codec).await
        }
        /// PutFile creates / replaces / appends a file in a single unary RPC.
        /// Server rejects requests with len(data) > 4 MiB (clients must use multipart).
        pub async fn put_file(
            &mut self,
            request: impl tonic::IntoRequest<super::PutFileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PutFileResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/fsplane.v1.FsPlane/PutFile",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("fsplane.v1.FsPlane", "PutFile"));
            self.inner.unary(req, path, codec).await
        }
        /// BeginWrite opens a multipart upload session. Returns an opaque upload_id
        /// that the caller uses for WriteParts / CommitWrite / AbortWrite.
        pub async fn begin_write(
            &mut self,
            request: impl tonic::IntoRequest<super::BeginWriteRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BeginWriteResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/fsplane.v1.FsPlane/BeginWrite",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("fsplane.v1.FsPlane", "BeginWrite"));
            self.inner.unary(req, path, codec).await
        }
        /// WriteParts streams data into an open upload. Single-writer per upload_id
        /// by construction (one streaming RPC == one writer). offset in each
        /// WritePartRequest MUST equal the server's cumulative bytes_received.
        /// Stream EOS means "data phase done, awaiting CommitWrite" — NOT commit.
        pub async fn write_parts(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::WritePartRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WritePartsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/fsplane.v1.FsPlane/WriteParts",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("fsplane.v1.FsPlane", "WriteParts"));
            self.inner.client_streaming(req, path, codec).await
        }
        /// CommitWrite publishes the multipart upload atomically (temp + rename for
        /// REPLACE / CREATE_ONLY; flock + seek-end + write for APPEND). Idempotent
        /// within the server's receipt retention window.
        pub async fn commit_write(
            &mut self,
            request: impl tonic::IntoRequest<super::CommitWriteRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CommitWriteResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/fsplane.v1.FsPlane/CommitWrite",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("fsplane.v1.FsPlane", "CommitWrite"));
            self.inner.unary(req, path, codec).await
        }
        /// AbortWrite discards an upload. Idempotent; safe on terminal sessions;
        /// TTL is the authoritative backstop if the client never calls this.
        pub async fn abort_write(
            &mut self,
            request: impl tonic::IntoRequest<super::AbortWriteRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AbortWriteResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/fsplane.v1.FsPlane/AbortWrite",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("fsplane.v1.FsPlane", "AbortWrite"));
            self.inner.unary(req, path, codec).await
        }
        /// WriteAt writes data at a specific offset on an existing file. Does not
        /// truncate. Unary — for bounded regions up to 4 MiB.
        pub async fn write_at(
            &mut self,
            request: impl tonic::IntoRequest<super::WriteAtRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WriteAtResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/fsplane.v1.FsPlane/WriteAt",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("fsplane.v1.FsPlane", "WriteAt"));
            self.inner.unary(req, path, codec).await
        }
        /// Truncate changes file size. Smaller = discard. Larger = zero-extend.
        pub async fn truncate(
            &mut self,
            request: impl tonic::IntoRequest<super::TruncateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TruncateResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/fsplane.v1.FsPlane/Truncate",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("fsplane.v1.FsPlane", "Truncate"));
            self.inner.unary(req, path, codec).await
        }
        /// Readdir lists entries in a directory.
        pub async fn readdir(
            &mut self,
            request: impl tonic::IntoRequest<super::ReaddirRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ReaddirResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/fsplane.v1.FsPlane/Readdir",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("fsplane.v1.FsPlane", "Readdir"));
            self.inner.unary(req, path, codec).await
        }
        /// Delete removes a file or empty directory.
        pub async fn delete(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteRequest>,
        ) -> std::result::Result<tonic::Response<super::DeleteResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/fsplane.v1.FsPlane/Delete",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("fsplane.v1.FsPlane", "Delete"));
            self.inner.unary(req, path, codec).await
        }
        /// Mkdir creates a directory. Supports recursive creation.
        pub async fn mkdir(
            &mut self,
            request: impl tonic::IntoRequest<super::MkdirRequest>,
        ) -> std::result::Result<tonic::Response<super::MkdirResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/fsplane.v1.FsPlane/Mkdir");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("fsplane.v1.FsPlane", "Mkdir"));
            self.inner.unary(req, path, codec).await
        }
        /// Rename moves/renames a file or directory.
        pub async fn rename(
            &mut self,
            request: impl tonic::IntoRequest<super::RenameRequest>,
        ) -> std::result::Result<tonic::Response<super::RenameResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/fsplane.v1.FsPlane/Rename",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("fsplane.v1.FsPlane", "Rename"));
            self.inner.unary(req, path, codec).await
        }
        /// Symlink creates a symbolic link.
        pub async fn symlink(
            &mut self,
            request: impl tonic::IntoRequest<super::SymlinkRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SymlinkResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/fsplane.v1.FsPlane/Symlink",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("fsplane.v1.FsPlane", "Symlink"));
            self.inner.unary(req, path, codec).await
        }
        /// Readlink returns the target of a symbolic link.
        pub async fn readlink(
            &mut self,
            request: impl tonic::IntoRequest<super::ReadlinkRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ReadlinkResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/fsplane.v1.FsPlane/Readlink",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("fsplane.v1.FsPlane", "Readlink"));
            self.inner.unary(req, path, codec).await
        }
        /// Chmod changes file/directory permissions.
        pub async fn chmod(
            &mut self,
            request: impl tonic::IntoRequest<super::ChmodRequest>,
        ) -> std::result::Result<tonic::Response<super::ChmodResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/fsplane.v1.FsPlane/Chmod");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("fsplane.v1.FsPlane", "Chmod"));
            self.inner.unary(req, path, codec).await
        }
        /// AdvanceNextChunk advances the JuiceFS nextChunk counter by the given offset.
        /// Must be called after TiKV BR clone to prevent slice ID collision between
        /// the original and cloned volumes.
        pub async fn advance_next_chunk(
            &mut self,
            request: impl tonic::IntoRequest<super::AdvanceNextChunkRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AdvanceNextChunkResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/fsplane.v1.FsPlane/AdvanceNextChunk",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("fsplane.v1.FsPlane", "AdvanceNextChunk"));
            self.inner.unary(req, path, codec).await
        }
        /// Flush forces buffered writes for a file to be committed.
        /// Only meaningful when prior mutations used flush=false (batch mode).
        pub async fn flush(
            &mut self,
            request: impl tonic::IntoRequest<super::FlushRequest>,
        ) -> std::result::Result<tonic::Response<super::FlushResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/fsplane.v1.FsPlane/Flush");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("fsplane.v1.FsPlane", "Flush"));
            self.inner.unary(req, path, codec).await
        }
        /// Ping is a liveness check.
        pub async fn ping(
            &mut self,
            request: impl tonic::IntoRequest<super::PingRequest>,
        ) -> std::result::Result<tonic::Response<super::PingResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/fsplane.v1.FsPlane/Ping");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("fsplane.v1.FsPlane", "Ping"));
            self.inner.unary(req, path, codec).await
        }
    }
}
