#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   ./scripts/pg_catalog_smoke.sh "postgresql://user:pass@host:5433/postgres?sslmode=require"
CONN="${1:?missing connection string}"
PSQL_BIN="${PSQL_BIN:-psql}"
LOG="${LOG:-pg_catalog_smoke.log}"

if ! command -v "$PSQL_BIN" >/dev/null 2>&1; then
  echo "[FAIL] psql not found: $PSQL_BIN"
  exit 1
fi

if command -v rg >/dev/null 2>&1; then
  GREP_BIN="rg"
else
  GREP_BIN="grep"
fi

psql_exec() {
  "$PSQL_BIN" "$CONN" -X -v ON_ERROR_STOP=1 "$@"
}

echo "[info] psql: $($PSQL_BIN --version)"
echo "[info] writing log to: $LOG"
: >"$LOG"

# 1) Phase A: exact regression path from user report.
psql_exec <<'SQL'
DROP TABLE IF EXISTS public.blog_chunks CASCADE;
CREATE TABLE public.blog_chunks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_url text NOT NULL,
  content text NOT NULL,
  lang text
);
INSERT INTO public.blog_chunks(source_url, content, lang)
VALUES ('https://example.com/x', 'x', 'en');
SQL

# Log hidden SQL emitted by psql metacommands (`-E`).
"$PSQL_BIN" "$CONN" -X -E -v ON_ERROR_STOP=1 >"$LOG" 2>&1 <<'PSQL'
\pset pager off
\conninfo
SELECT version();
\dt
\d blog_chunks
\d blog_chunks
\d
\d+ blog_chunks
\d blog_chunks
PSQL

# 2) Phase B: broader pg_catalog coverage with portable objects.
psql_exec <<'SQL'
DROP SCHEMA IF EXISTS cat_smoke CASCADE;
CREATE SCHEMA cat_smoke;

CREATE TYPE cat_smoke.status_enum AS ENUM ('new','done');

CREATE TABLE cat_smoke.accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL,
  name text NOT NULL,
  status cat_smoke.status_enum NOT NULL DEFAULT 'new',
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT accounts_name_nonempty CHECK (char_length(name) > 0)
);

CREATE TABLE cat_smoke.child_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT NOT NULL,
  note text,
  CONSTRAINT fk_accounts
    FOREIGN KEY (account_id)
    REFERENCES cat_smoke.accounts(id)
);

CREATE TABLE cat_smoke.blog_chunks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_url text NOT NULL,
  content text NOT NULL,
  content_tsv tsvector,
  lang text
);
CREATE INDEX idx_blog_chunks_source_url ON cat_smoke.blog_chunks (source_url);
CREATE INDEX idx_blog_chunks_content_gin ON cat_smoke.blog_chunks USING gin (content_tsv);

CREATE VIEW cat_smoke.v_accounts AS
  SELECT id, email, status, created_at FROM cat_smoke.accounts;

CREATE MATERIALIZED VIEW cat_smoke.mv_accounts AS
  SELECT status, count(*) AS cnt FROM cat_smoke.accounts GROUP BY status;

INSERT INTO cat_smoke.accounts(email, name) VALUES ('a@test.com', 'alice');
INSERT INTO cat_smoke.blog_chunks(source_url, content, content_tsv, lang)
VALUES ('https://example.com/y', 'y', to_tsvector('simple', 'y'), 'en');
ANALYZE cat_smoke.accounts;
SQL

# Append extended metacommand coverage.
"$PSQL_BIN" "$CONN" -X -E -v ON_ERROR_STOP=1 >>"$LOG" 2>&1 <<'PSQL'
\pset pager off
\dn
\dT cat_smoke.*
\dt cat_smoke.*
\di cat_smoke.*
\dv cat_smoke.*
\dm cat_smoke.*

\d cat_smoke.accounts
\d+ cat_smoke.accounts
\d cat_smoke.blog_chunks
\d+ cat_smoke.blog_chunks
\d cat_smoke.child_notes
\d+ cat_smoke.child_notes
\d cat_smoke.v_accounts
\d cat_smoke.mv_accounts
\d+ cat_smoke.mv_accounts
PSQL

# 3) Cleanup test objects.
psql_exec <<'SQL'
DROP SCHEMA IF EXISTS cat_smoke CASCADE;
DROP TABLE IF EXISTS public.blog_chunks;
SQL

# 4) Fail-fast rule
if [ "$GREP_BIN" = "rg" ]; then
  if rg -n 'ERROR:|FATAL:|PANIC:' "$LOG" >/dev/null; then
    echo "[FAIL] pg_catalog smoke failed. See $LOG"
    rg -n 'ERROR:|FATAL:|PANIC:' "$LOG"
    exit 1
  fi
else
  if grep -En 'ERROR:|FATAL:|PANIC:' "$LOG" >/dev/null; then
    echo "[FAIL] pg_catalog smoke failed. See $LOG"
    grep -En 'ERROR:|FATAL:|PANIC:' "$LOG"
    exit 1
  fi
fi

echo "[PASS] pg_catalog smoke passed"
