#!/usr/bin/env python3
"""Parse `go test -json` output from the pgx suite -> regenerate pgx-bank.md.

Records every failing test verbatim (package::Test + the real db9 error) grouped
by root cause. pgx is Go's PostgreSQL driver; its suite hammers the connect-path
surface (extended protocol, binary type/OID codecs, COPY, pipelining) like
psycopg, from a different (Go) implementation.

Usage: classify_failures.py <go-test-json-file> <output_md>
"""
import json
import re
import sys
from collections import Counter, defaultdict

KNOWN = [
    ("could not determine data type of parameter", ("Extended-protocol parameter type inference ($N indeterminate)", "types/protocol")),
    ("already exists", ("relation already exists — test-isolation/cleanup (tests reuse table names; db9 cleanup/temp-table behavior)", "cascade/isolation")),
    ("GENERATE_SERIES is a set-returning function", ("generate_series() unsupported in this context", "functions/srf")),
    ('type "inet', ("inet/inet[] type missing", "types")),
    ("statement timeout", ("statement_timeout firing (db9 default 60s; PG default 0/unlimited)", "session/timeout")),
    ("found: range", ("range-type DDL not parsed", "parser/types")),
    ("INT8RANGE", ("range-type constructors unsupported (int8range, …)", "functions/types")),
    ("INT4RANGE", ("range-type constructors unsupported (int4range, …)", "functions/types")),
    ("array header too short", ("array binary codec mismatch", "wire/codec")),
    ('type "uint', ("custom/unsigned type unsupported (pgx-specific)", "types")),
    ("transaction_read_only", ("transaction_read_only GUC unrecognized", "session/guc")),
    ("current transaction is aborted", ("cascade (downstream of a prior error)", "cascade")),
    ("does not exist", ("relation/object missing — cascade of a failed setup statement", "cascade")),
]


def classify(msg):
    for sub, info in KNOWN:
        if sub.lower() in msg.lower():
            return info
    if re.search(r"expected|got nil|An error is expected", msg):
        return ("result/behavior mismatch (assertion)", "behavior")
    return ("untriaged", "—")


def real_err(body):
    lines = [l.rstrip() for l in body.splitlines()]
    for l in lines:
        if re.search(r"ERROR:|SQLSTATE|does not exist|not supported|unknown |cannot |unrecognized|too short", l):
            return l.strip()
    for i, l in enumerate(lines):
        if "unexpected error" in l.lower() and i + 1 < len(lines):
            return lines[i + 1].strip()
    for l in lines:
        if re.search(r"expected|got |FAIL|Error:", l):
            return l.strip()
    return "(no clear error)"


def main():
    jsonfile, out_md = sys.argv[1], sys.argv[2]
    npass = nfail = nskip = 0
    fails = {}
    out = defaultdict(list)
    pkgfail = Counter()
    for line in open(jsonfile, errors="replace"):
        line = line.strip()
        if not line.startswith("{"):
            continue
        try:
            e = json.loads(line)
        except Exception:
            continue
        a, t, p = e.get("Action"), e.get("Test"), e.get("Package", "")
        if not t:
            continue
        if a == "pass":
            npass += 1
        elif a == "skip":
            nskip += 1
        elif a == "fail":
            nfail += 1
            fails[(p, t)] = True
            pkgfail[p.split("/")[-1]] += 1
        elif a == "output":
            out[(p, t)].append(e.get("Output", ""))

    groups = defaultdict(list)
    for k in fails:
        err = real_err("".join(out.get(k, [])))
        groups[classify(err)].append((k[0].split("/")[-1], k[1], err))

    total = npass + nfail + nskip
    o = []
    W = o.append
    W("# pgx Driver Bank — db9 PostgreSQL-Compatibility Validation\n")
    W("> Auto-generated by `classify_failures.py` from `go test -json`. Runs **pgx's own")
    W("> test suite** (Go's PG driver) against db9 — the connect-path surface (extended")
    W("> protocol, binary type/OID codecs, COPY, pipelining) from a different impl than")
    W("> psycopg. Re-run: `bash auto_testing/corpora/drivers/pgx/run.sh`.\n")
    W(f"**Tests:** {total} · **Pass:** {npass} ({round(100*npass/total) if total else 0}%) · "
      f"**Fail:** {nfail} · **Skip:** {nskip}\n")
    W("> Note: `relation already exists` failures (~110) are largely **test-isolation** — pgx")
    W("> tests reuse fixed table names and rely on per-test cleanup; on db9 the residue makes")
    W("> later tests collide. Partly a db9 cleanup/temp-table behavior, partly test design —")
    W("> not ~110 independent bugs.\n")
    W("## Failures per package\n")
    W("| Package | Failures |")
    W("|---|---|")
    for p, c in pkgfail.most_common():
        W(f"| {p} | {c} |")
    W("")
    W("## Root causes (by blast radius)\n")
    W("| Root cause | Fault layer | Cases |")
    W("|---|---|---|")
    for (name, layer), items in sorted(groups.items(), key=lambda x: -len(x[1])):
        W(f"| {name} | {layer} | {len(items)} |")
    W("")
    W("## Every failing case (verbatim)\n")
    W("| Package | Test | db9 error (verbatim) |")
    W("|---|---|---|")
    for k in sorted(fails):
        pkg = k[0].split("/")[-1]
        err = real_err("".join(out.get(k, []))).replace("|", chr(92) + "|")[:200]
        W(f"| {pkg} | `{k[1]}` | {err} |")
    W("")
    W("## Reproduce\n```bash")
    W("bash auto_testing/corpora/drivers/pgx/run.sh      # full (go test -json vs db9)")
    W("# single test (db9 on :5455):")
    W('PGX_TEST_DATABASE="postgres://admin:admin@127.0.0.1:5455/pgx_test" \\')
    W("  go test -run TestName -v ./... -count=1   # from the pgx checkout")
    W("```")
    open(out_md, "w").write("\n".join(o))
    print(f"wrote {out_md}: {total} tests, {nfail} failures, {len(groups)} root-cause groups")


if __name__ == "__main__":
    main()
